using System;using System.Collections.Generic;using System.IO;using System.Net.Http;using System.Text.Json;using System.Windows;using System.Windows.Controls;
namespace Alpha6Ops.Desktop;
public partial class DispatchWorkspace:UserControl
{
 ActiveFlightPlan? activePlan;SimBriefImport? draft;bool acceptedReview;internal event EventHandler? DashboardRequested;internal event EventHandler? ManualRequested;internal event EventHandler<ActiveFlightPlan>? FlightAccepted;internal event EventHandler? TrackingRequested;internal bool HasActiveRelease=>activePlan is not null;
 private string? stateDirectory;
 public DispatchWorkspace(){InitializeComponent();}
 internal void SetDataDirectory(string directory){stateDirectory=directory;SimBriefUsernameBox.Text=SimBriefImporter.LoadUsername(stateDirectory);}
 internal void Render(ActiveFlightPlan? plan,string state){activePlan=plan;ReleaseStateText.Text=draft is not null?"REVIEW REQUIRED":plan is null?"NO RELEASE":state;CurrentStateText.Text=state;ShowState();if(plan is null)return;FlightNumberText.Text=plan.FlightNumber;OriginText.Text=plan.Origin;DestinationText.Text=plan.Destination;DepartureText.Text=Utc(plan.PlannedDepartureUtc);ArrivalText.Text=Utc(plan.PlannedArrivalUtc);AircraftText.Text=Val(plan.AircraftType,"NOT ASSIGNED");SourceText.Text=Val(plan.Source,"PILOT ENTRY").ToUpperInvariant();ActiveOfpButton.IsEnabled=!string.IsNullOrWhiteSpace(plan.OfpCacheKey);}
 void ShowState(){EmptyState.Visibility=draft is null&&activePlan is null?Visibility.Visible:Visibility.Collapsed;ReviewState.Visibility=draft is null?Visibility.Collapsed:Visibility.Visible;ActiveState.Visibility=draft is null&&activePlan is not null?Visibility.Visible:Visibility.Collapsed;}
 async void Import_Click(object s,RoutedEventArgs e)=>await ImportAsync();async void Refresh_Click(object s,RoutedEventArgs e)=>await ImportAsync();async void ImportNew_Click(object s,RoutedEventArgs e){SimBriefUsernameBox.Text=activePlan?.SimBriefUsername??SimBriefImporter.LoadUsername(stateDirectory);await ImportAsync();}
 async System.Threading.Tasks.Task ImportAsync(){ImportButton.IsEnabled=false;AcceptButton.IsEnabled=false;ImportStatusText.Text="Downloading latest SimBrief briefing…";try{PresentDraft(await SimBriefImporter.ImportAsync(SimBriefUsernameBox.Text, root: stateDirectory));}catch(Exception x)when(x is IOException or HttpRequestException or JsonException or ArgumentException){ImportStatusText.Text=x.GetBaseException().Message;ReviewNoticeText.Text=ImportStatusText.Text;}finally{ImportButton.IsEnabled=true;}}
 internal void PresentDraft(SimBriefImport release){acceptedReview=false;draft=release;RenderDraft(release);ShowState();ReleaseStateText.Text="REVIEW REQUIRED";var age=DateTimeOffset.UtcNow-release.GeneratedUtc;var issues=ValidationIssues(release.Plan);var same=SameRelease(activePlan,release.Plan);var relation=same?"UNCHANGED FROM ACTIVE RELEASE":activePlan is null?"NEW RELEASE":release.GeneratedUtc>(activePlan.ImportedAtUtc??DateTimeOffset.MinValue)?"NEWER RELEASE":"DIFFERENT RELEASE";ReviewNoticeText.Text=$"{(release.FromCache?"OFFLINE CACHED RELEASE":"LATEST SIMBRIEF RELEASE")} • {relation} • GENERATED {release.GeneratedUtc.UtcDateTime:dd MMM yyyy HH:mm}Z"+(age>TimeSpan.FromHours(24)?" • REVIEW: MORE THAN 24 HOURS OLD":"")+(issues.Count>0?" • REQUIRED: "+string.Join(", ",issues):"");AcceptButton.IsEnabled=!same&&issues.Count==0;AcceptButton.Content=same?"ACTIVE RELEASE IS CURRENT":issues.Count>0?"RELEASE NEEDS ATTENTION":"ACCEPT FLIGHT";}
 void RenderDraft(SimBriefImport r){var p=r.Plan;ReviewFlightNumberText.Text=p.FlightNumber;ReviewOriginText.Text=p.Origin;ReviewDestinationText.Text=p.Destination;ReviewAircraftText.Text=Val(p.AircraftType,"NOT PROVIDED");ReviewRegistrationText.Text=Val(p.Registration,"NOT PROVIDED");ReviewDistanceText.Text=r.DistanceNm is{} d?$"{d:0} NM":"NOT PROVIDED";ReviewDepartureText.Text=Utc(p.PlannedDepartureUtc);ReviewArrivalText.Text=Utc(p.PlannedArrivalUtc);ReviewDurationText.Text=$"{p.PlannedDuration.TotalHours:0}H {p.PlannedDuration.Minutes:00}M";ReviewRouteText.Text=Val(r.Route,"DIRECT / NOT PROVIDED");ReviewRampFuelText.Text=Measure(r.RampFuel,r.FuelUnits);ReviewTripFuelText.Text=Measure(p.PlannedTripFuel,r.FuelUnits);ReviewPayloadText.Text=Measure(r.PayloadWeight,r.WeightUnits);ReviewPassengersText.Text=r.Passengers?.ToString()??"NOT PROVIDED";DraftOfpButton.Content=r.HasOfpText||r.HasOfpPdf?"VIEW OFP":"VIEW OFP • UNAVAILABLE";}
 async void Accept_Click(object s,RoutedEventArgs e)
 {
  if(acceptedReview){TrackingRequested?.Invoke(this,EventArgs.Empty);return;}
  if(draft?.Plan is not{IsValid:true} plan||!AcceptButton.IsEnabled)return;
  if(activePlan is not null&&!SameRelease(activePlan,plan)){var owner=Window.GetWindow(this);if(owner is null||!OpsConfirmWindow.Ask(owner,"Replace active flight",$"{activePlan.FlightNumber} • {activePlan.Origin} → {activePlan.Destination} will be replaced by {plan.FlightNumber} • {plan.Origin} → {plan.Destination}."))return;}
  AcceptButton.IsEnabled=DraftOfpButton.IsEnabled=RefreshButton.IsEnabled=CancelReviewButton.IsEnabled=false;
  try
  {
   for(var frame=0;frame<7;frame++){AcceptButton.Content="SENDING TO DISPATCH"+new string('.',frame%4);await System.Threading.Tasks.Task.Delay(220);}
   FlightAccepted?.Invoke(this,plan);activePlan=plan;acceptedReview=true;ReleaseStateText.Text="FLIGHT ACCEPTED";ReviewNoticeText.Text="FLIGHT ACCEPTED • RELEASE SAVED LOCALLY • READY FOR FLIGHT TRACKING";AcceptButton.Content="VIEW FLIGHT TRACKING";AcceptButton.IsEnabled=true;DraftOfpButton.IsEnabled=RefreshButton.IsEnabled=CancelReviewButton.IsEnabled=true;
  }
  catch(Exception error) when(error is IOException or UnauthorizedAccessException or InvalidOperationException){ReviewNoticeText.Text="DISPATCH COULD NOT ACCEPT THE FLIGHT • "+error.GetBaseException().Message;AcceptButton.Content="TRY ACCEPT FLIGHT AGAIN";AcceptButton.IsEnabled=DraftOfpButton.IsEnabled=RefreshButton.IsEnabled=CancelReviewButton.IsEnabled=true;}
 }
 internal void DiscardDraft(){acceptedReview=false;draft=null;ImportStatusText.Text="";Render(activePlan,activePlan is null?"IMPORT FLIGHT":"VIEW RELEASE");}void CancelReview_Click(object s,RoutedEventArgs e)=>DiscardDraft();void Back_Click(object s,RoutedEventArgs e)=>DashboardRequested?.Invoke(this,EventArgs.Empty);void Manual_Click(object s,RoutedEventArgs e)=>ManualRequested?.Invoke(this,EventArgs.Empty);void Tracking_Click(object s,RoutedEventArgs e)=>TrackingRequested?.Invoke(this,EventArgs.Empty);void DraftOfp_Click(object s,RoutedEventArgs e){if(draft is not null)OpenOfp(draft.Plan);}void ActiveOfp_Click(object s,RoutedEventArgs e){if(activePlan is not null)OpenOfp(activePlan);}void OpenOfp(ActiveFlightPlan plan){new OfpViewerWindow(plan, stateDirectory){Owner=Window.GetWindow(this)}.ShowDialog();}void CopyDraftRoute_Click(object s,RoutedEventArgs e){if(draft?.Route is{Length:>0} route)Clipboard.SetText(route);}
 internal static IReadOnlyList<string> ValidationIssues(ActiveFlightPlan plan){var issues=new System.Collections.Generic.List<string>();if(!plan.IsValid)issues.Add("valid airports and schedule");if(string.IsNullOrWhiteSpace(plan.AircraftType))issues.Add("aircraft");if(string.IsNullOrWhiteSpace(plan.Route))issues.Add("route");return issues;}
 internal static bool SameRelease(ActiveFlightPlan? current,ActiveFlightPlan candidate)=>current is not null&&((!string.IsNullOrWhiteSpace(current.OfpCacheKey)&&current.OfpCacheKey==candidate.OfpCacheKey)||(current.FlightNumber==candidate.FlightNumber&&current.Origin==candidate.Origin&&current.Destination==candidate.Destination&&current.PlannedDepartureUtc==candidate.PlannedDepartureUtc&&current.PlannedArrivalUtc==candidate.PlannedArrivalUtc&&current.Route==candidate.Route));
 static string Utc(DateTimeOffset v)=>v.UtcDateTime.ToString("dd MMM yyyy • HH:mm'Z'");static string Val(string? v,string f)=>string.IsNullOrWhiteSpace(v)?f:v;static string Measure(double? v,string? u)=>v is{} n?$"{n:N0} {Val(u,"UNITS")}":"NOT PROVIDED";
}
