using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Alpha6Ops.Accounts.Migrations;

[DbContext(typeof(AccountsDbContext))]
[Migration("202609190001_DataProtectionKeys")]
public sealed class DataProtectionKeys : Migration
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) => DataProtectionKeysModel.Build(modelBuilder);

    // The key ring for cookie and antiforgery protection. Each row is one XML key element as ASP.NET Core
    // writes it, already encrypted with the configured certificate; the table is never edited by hand.
    protected override void Up(MigrationBuilder migrationBuilder) => migrationBuilder.Sql("""
        CREATE TABLE data_protection_key (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_data_protection_key" PRIMARY KEY,
            "FriendlyName" varchar(120) NOT NULL,
            "Xml" text NOT NULL);
        """);

    protected override void Down(MigrationBuilder migrationBuilder) => migrationBuilder.Sql("DROP TABLE data_protection_key;");
}

internal static class DataProtectionKeysModel
{
    internal static void Build(ModelBuilder model)
    {
        LogbookAndMediaModel.Build(model);
        model.Entity("Alpha6Ops.Accounts.DataProtectionKey", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("FriendlyName").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
            b.Property<string>("Xml").IsRequired().HasColumnType("text");
            b.HasKey("Id"); b.ToTable("data_protection_key");
        });
    }
}
